FROM node:20-alpine as build

WORKDIR /dash

COPY . .

RUN yarn install
COPY . .

WORKDIR /dash/client

COPY ./client/package*.json ./

RUN yarn workspaces focus -A

COPY ./client .

RUN yarn build

RUN ls -la . && echo "ls ."

RUN ls -la /dash/client/dist && echo "ls ./client/dist/"
RUN ls -la /dash/server/ && echo "ls /dash/server/"
COPY ./client/dist /dash/server/public

RUN ls -la /dash/server/public && echo "ls /dash/server/public/"

# COPY ./client/503.html /usr/share/nginx/html/