FROM node:20-alpine as build

WORKDIR /dash

COPY . .

RUN yarn install
COPY . .

WORKDIR /dash/client

COPY ./client/package*.json ./

# do the following 2 lines work?
RUN yarn workspaces focus -A

COPY ./client .

RUN yarn build

FROM nginx:alpine

COPY --from=build /dash/client/dist /usr/share/nginx/html