/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyMeRouteImport } from "./routes/verify-me"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"

const PriceActionDailyRecapLazyRouteImport = createFileRoute(
  "/price-action/daily-recap",
)()

const VerifyMeRoute = VerifyMeRouteImport.update({
  id: "/verify-me",
  path: "/verify-me",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PriceActionDailyRecapLazyRoute =
  PriceActionDailyRecapLazyRouteImport.update({
    id: "/price-action/daily-recap",
    path: "/price-action/daily-recap",
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import("./routes/price-action/daily-recap.lazy").then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/register": typeof RegisterRoute
  "/verify-me": typeof VerifyMeRoute
  "/price-action/daily-recap": typeof PriceActionDailyRecapLazyRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/register": typeof RegisterRoute
  "/verify-me": typeof VerifyMeRoute
  "/price-action/daily-recap": typeof PriceActionDailyRecapLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/register": typeof RegisterRoute
  "/verify-me": typeof VerifyMeRoute
  "/price-action/daily-recap": typeof PriceActionDailyRecapLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/register"
    | "/verify-me"
    | "/price-action/daily-recap"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/register" | "/verify-me" | "/price-action/daily-recap"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/register"
    | "/verify-me"
    | "/price-action/daily-recap"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RegisterRoute: typeof RegisterRoute
  VerifyMeRoute: typeof VerifyMeRoute
  PriceActionDailyRecapLazyRoute: typeof PriceActionDailyRecapLazyRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-me": {
      id: "/verify-me"
      path: "/verify-me"
      fullPath: "/verify-me"
      preLoaderRoute: typeof VerifyMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/price-action/daily-recap": {
      id: "/price-action/daily-recap"
      path: "/price-action/daily-recap"
      fullPath: "/price-action/daily-recap"
      preLoaderRoute: typeof PriceActionDailyRecapLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RegisterRoute: RegisterRoute,
  VerifyMeRoute: VerifyMeRoute,
  PriceActionDailyRecapLazyRoute: PriceActionDailyRecapLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
